/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: schema.json
export type Publication = {
  _id: string
  _type: 'publication'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author?: string
  title?: string
  volume?: number
  issue?: number
  pages?: string
  journal?: string
  doi?: string
  url?: string
  abstract?: string
  date?: string
}

export type Timeline = {
  _type: 'timeline'
  hidden?: boolean
  items?: Array<{
    title?: string
    milestones?: Array<
      {
        _key: string
      } & Milestone
    >
    _type: 'item'
    _key: string
  }>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Milestone = {
  _type: 'milestone'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tags?: Array<string>
  duration?: Duration
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  duration?: Duration
  category?: string
  status?: 'active' | 'completed' | 'seeking-students'
  site?: string
  tags?: Array<string>
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Timeline)
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Duration = {
  _type: 'duration'
  start?: string
  end?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              href?: string
              _type: 'link'
              _key: string
            }
          | {
              reference?: PageReference
              _type: 'internalLink'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Timeline)
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type ProfileReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'profile'
}

export type HomeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'home'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteName?: string
  shortName?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  logoDark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  brandColor?: Color
  theme?: 'default' | 'warm'
  labHead?: ProfileReference
  showLabHeadOnHome?: boolean
  menuItems?: ArrayOf<HomeReference | PageReference | ProjectReference>
  showPublications?: boolean
  showPeople?: boolean
  showContactForm?: boolean
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type RoleGroupReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'roleGroup'
}

export type Profile = {
  _id: string
  _type: 'profile'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  name?: string
  role?: string
  roleGroup?: RoleGroupReference
  email?: string
  phone?: string
  bio?: string
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  slug?: Slug
  hasPage?: boolean
}

export type RoleGroup = {
  _id: string
  _type: 'roleGroup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title?: string
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  showcaseProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MediaFolderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'media.folder'
}

export type MediaFolder = {
  _id: string
  _type: 'media.folder'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  parent?: MediaFolderReference
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Publication
  | Timeline
  | SanityImageAssetReference
  | Milestone
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Duration
  | Slug
  | PageReference
  | Page
  | ProfileReference
  | HomeReference
  | ProjectReference
  | Settings
  | RoleGroupReference
  | Profile
  | RoleGroup
  | Color
  | Home
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: lib/sanity.queries.ts
// Variable: homePageQuery
// Query: *[_type == "home"][0]{    _id,    overview,    showcaseProjects[]->{      _type,      coverImage,      overview,      "slug": slug.current,      tags,      title,    },    title,  }
export type HomePageQueryResult = {
  _id: string
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  showcaseProjects: Array<{
    _type: 'project'
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    overview: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: null
      level?: number
      _type: 'block'
      _key: string
    }> | null
    slug: string | null
    tags: Array<string> | null
    title: string | null
  }> | null
  title: string | null
} | null

// Source: lib/sanity.queries.ts
// Variable: homePageTitleQuery
// Query: *[_type == "home"][0].title
export type HomePageTitleQueryResult = string | null

// Source: lib/sanity.queries.ts
// Variable: pagesBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    body[]{      ...,      _type == "block" => {        markDefs[]{          ...,          _type == "internalLink" => {            "slug": reference->slug.current,            "title": reference->title,          }        }      }    },    overview,    title,    "slug": slug.current,  }
export type PagesBySlugQueryResult = {
  _id: string
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<
          | {
              reference?: PageReference
              _type: 'internalLink'
              _key: string
              slug: string | null
              title: string | null
            }
          | {
              href?: string
              _type: 'link'
              _key: string
            }
        > | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'timeline'
        hidden?: boolean
        items?: Array<{
          title?: string
          milestones?: Array<
            {
              _key: string
            } & Milestone
          >
          _type: 'item'
          _key: string
        }>
      }
  > | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  title: string | null
  slug: string | null
} | null

// Source: lib/sanity.queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    category,    coverImage,    description,    duration,    overview,    site,    "slug": slug.current,    status,    tags,    title,  }
export type ProjectBySlugQueryResult = {
  _id: string
  category: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  description: Array<
    | ({
        _key: string
      } & Timeline)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  > | null
  duration: Duration | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  site: string | null
  slug: string | null
  status: 'active' | 'completed' | 'seeking-students' | null
  tags: Array<string> | null
  title: string | null
} | null

// Source: lib/sanity.queries.ts
// Variable: projectPaths
// Query: *[_type == "project" && slug.current != null].slug.current
export type ProjectPathsResult = Array<string | null>

// Source: lib/sanity.queries.ts
// Variable: pagePaths
// Query: *[_type == "page" && slug.current != null].slug.current
export type PagePathsResult = Array<string | null>

// Source: lib/sanity.queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{    siteName,    shortName,    footer,    showPublications,    showPeople,    showContactForm,    showLabHeadOnHome,    menuItems[]->{      _type,      "slug": slug.current,      title    },    ogImage,    brandColor{hex},    theme,    logo{      ...,      asset->{        ...,        metadata { dimensions { aspectRatio } }      }    },    logoDark{      ...,      asset->{        ...,        metadata { dimensions { aspectRatio } }      }    },    labHead->{      _id,      image,      name,      role,      email,      phone,      bio,      "slug": slug.current,      hasPage,      fullBio,    },  }
export type SettingsQueryResult = {
  siteName: string | null
  shortName: string | null
  footer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  showPublications: boolean | null
  showPeople: boolean | null
  showContactForm: boolean | null
  showLabHeadOnHome: boolean | null
  menuItems: Array<
    | {
        _type: 'home'
        slug: null
        title: string | null
      }
    | {
        _type: 'page'
        slug: string | null
        title: string | null
      }
    | {
        _type: 'project'
        slug: string | null
        title: string | null
      }
  > | null
  ogImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  brandColor: {
    hex: string | null
  } | null
  theme: 'default' | 'warm' | null
  logo: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata: {
        dimensions: {
          aspectRatio: number | null
        } | null
      } | null
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  logoDark: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata: {
        dimensions: {
          aspectRatio: number | null
        } | null
      } | null
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  labHead: {
    _id: string
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    name: string | null
    role: string | null
    email: string | null
    phone: string | null
    bio: string | null
    slug: string | null
    hasPage: boolean | null
    fullBio: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  } | null
} | null

// Source: lib/sanity.queries.ts
// Variable: publicationsQuery
// Query: *[_type == "publication"] | order(date desc) {    _id,    title,    author,    journal,    volume,    issue,    pages,    abstract,    url,    doi,    date,  }
export type PublicationsQueryResult = Array<{
  _id: string
  title: string | null
  author: string | null
  journal: string | null
  volume: number | null
  issue: number | null
  pages: string | null
  abstract: string | null
  url: string | null
  doi: string | null
  date: string | null
}>

// Source: lib/sanity.queries.ts
// Variable: roleGroupQuery
// Query: *[_type == "roleGroup"] | order(orderRank) {    _id,    title,  }
export type RoleGroupQueryResult = Array<{
  _id: string
  title: string | null
}>

// Source: lib/sanity.queries.ts
// Variable: profileQuery
// Query: *[_type == "profile"] | order(orderRank) {    _id,    image,    orderRank,    name,    role,    roleGroup->{      _id,      title,    },    email,    phone,    bio,    "slug": slug.current,    hasPage,    fullBio,  }
export type ProfileQueryResult = Array<{
  _id: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  orderRank: string | null
  name: string | null
  role: string | null
  roleGroup: {
    _id: string
    title: string | null
  } | null
  email: string | null
  phone: string | null
  bio: string | null
  slug: string | null
  hasPage: boolean | null
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
}>

// Source: lib/sanity.queries.ts
// Variable: profileBySlugQuery
// Query: *[_type == "profile" && slug.current == $slug && hasPage == true][0]{    _id,    image,    name,    role,    email,    phone,    bio,    "slug": slug.current,    hasPage,    fullBio,  }
export type ProfileBySlugQueryResult = {
  _id: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  name: string | null
  role: string | null
  email: string | null
  phone: string | null
  bio: string | null
  slug: string | null
  hasPage: boolean | null
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
} | null

// Source: lib/sanity.queries.ts
// Variable: profilePaths
// Query: *[_type == "profile" && hasPage == true && slug.current != null].slug.current
export type ProfilePathsResult = Array<string | null>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    overview,\n    showcaseProjects[]->{\n      _type,\n      coverImage,\n      overview,\n      "slug": slug.current,\n      tags,\n      title,\n    },\n    title,\n  }\n': HomePageQueryResult
    '\n  *[_type == "home"][0].title\n': HomePageTitleQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    body[]{\n      ...,\n      _type == "block" => {\n        markDefs[]{\n          ...,\n          _type == "internalLink" => {\n            "slug": reference->slug.current,\n            "title": reference->title,\n          }\n        }\n      }\n    },\n    overview,\n    title,\n    "slug": slug.current,\n  }\n': PagesBySlugQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    category,\n    coverImage,\n    description,\n    duration,\n    overview,\n    site,\n    "slug": slug.current,\n    status,\n    tags,\n    title,\n  }\n': ProjectBySlugQueryResult
    '\n  *[_type == "project" && slug.current != null].slug.current\n': ProjectPathsResult
    '\n  *[_type == "page" && slug.current != null].slug.current\n': PagePathsResult
    '\n  *[_type == "settings"][0]{\n    siteName,\n    shortName,\n    footer,\n    showPublications,\n    showPeople,\n    showContactForm,\n    showLabHeadOnHome,\n    menuItems[]->{\n      _type,\n      "slug": slug.current,\n      title\n    },\n    ogImage,\n    brandColor{hex},\n    theme,\n    logo{\n      ...,\n      asset->{\n        ...,\n        metadata { dimensions { aspectRatio } }\n      }\n    },\n    logoDark{\n      ...,\n      asset->{\n        ...,\n        metadata { dimensions { aspectRatio } }\n      }\n    },\n    labHead->{\n      _id,\n      image,\n      name,\n      role,\n      email,\n      phone,\n      bio,\n      "slug": slug.current,\n      hasPage,\n      fullBio,\n    },\n  }\n': SettingsQueryResult
    '\n  *[_type == "publication"] | order(date desc) {\n    _id,\n    title,\n    author,\n    journal,\n    volume,\n    issue,\n    pages,\n    abstract,\n    url,\n    doi,\n    date,\n  }\n': PublicationsQueryResult
    '\n  *[_type == "roleGroup"] | order(orderRank) {\n    _id,\n    title,\n  }\n': RoleGroupQueryResult
    '\n  *[_type == "profile"] | order(orderRank) {\n    _id,\n    image,\n    orderRank,\n    name,\n    role,\n    roleGroup->{\n      _id,\n      title,\n    },\n    email,\n    phone,\n    bio,\n    "slug": slug.current,\n    hasPage,\n    fullBio,\n  }\n': ProfileQueryResult
    '\n  *[_type == "profile" && slug.current == $slug && hasPage == true][0]{\n    _id,\n    image,\n    name,\n    role,\n    email,\n    phone,\n    bio,\n    "slug": slug.current,\n    hasPage,\n    fullBio,\n  }\n': ProfileBySlugQueryResult
    '\n  *[_type == "profile" && hasPage == true && slug.current != null].slug.current\n': ProfilePathsResult
  }
}
