import type { Image } from 'sanity'
import type {
  HomePageQueryResult,
  HomeResourceQueryResult,
  HomeSiteCopyQueryResult,
  MaestroProjectQueryResult,
  PagesBySlugQueryResult,
  ProfileBySlugQueryResult,
  ProfileQueryResult,
  ProjectBySlugQueryResult,
  PublicationsQueryResult,
  ResearchProjectsQueryResult,
  ResourcesQueryResult,
  RoleGroupQueryResult,
  SettingsQueryResult,
  SupportPageQueryResult,
} from 'sanity.types'

export interface MilestoneItem {
  description?: string
  duration?: {
    start?: string
    end?: string
  }
  image?: Image
  tags?: string[]
  title?: string
}

// Page payloads — derived from `sanity.types.ts` (generated by `npm run typegen` from the actual
// GROQ queries in `lib/sanity.queries.ts`). Every field TypeGen says can be null is typed
// `T | null` here, not silently widened to non-null — callers must handle it explicitly.

export type HomePagePayload = NonNullable<HomePageQueryResult>
export type ShowcaseProject = NonNullable<
  HomePagePayload['showcaseProjects']
>[number]

export type PagePayload = NonNullable<PagesBySlugQueryResult>

export type ProjectPayload = NonNullable<ProjectBySlugQueryResult>

export type SettingsPayload = NonNullable<SettingsQueryResult>
export type MenuItem = NonNullable<SettingsPayload['menuItems']>[number]

export type PublicationPayload = PublicationsQueryResult[number]

export type ResourcePayload = ResourcesQueryResult[number]

export type ResearchProjectPayload = ResearchProjectsQueryResult[number]

export type ProfilePayload = ProfileQueryResult[number]
export type ProfileBySlugPayload = NonNullable<ProfileBySlugQueryResult>
export type LabHeadPayload = NonNullable<SettingsPayload['labHead']>

export type RoleGroupPayload = RoleGroupQueryResult[number]

// Home's own queries (Task 3 brief). `homeRecentPublicationsQuery` shares
// `publicationFields` with `publicationsQuery`, so its rows are typed as
// `PublicationPayload` directly rather than a second generated type --
// TypeGen still emits `HomeRecentPublicationsQueryResult` for it (same
// shape, different query string), but there's no reason to carry two
// structurally identical payload types through the app. Likewise
// `publicationCountQuery` is just `number` (TypeGen's own
// `PublicationCountQueryResult`), used directly at the one call site.
export type HomeResourcePayload = NonNullable<HomeResourceQueryResult>
export type MaestroProjectPayload = NonNullable<MaestroProjectQueryResult>
export type SupportPagePayload = NonNullable<SupportPageQueryResult>
export type SiteCopyPayload = NonNullable<HomeSiteCopyQueryResult>

// `SettingsPayload` now requires every key (nullable values are fine, but the keys themselves
// must be present) — the seven call sites that used to fall back to a bare `?? {}` need a real
// object satisfying that shape. Shared here so it's defined once, not duplicated seven times.
//
// The three `show*` booleans are `null`, not `false`: the pre-existing `?? {}` fallback left them
// `undefined`, which every consuming route's `=== false` notFound() guard treats as "unset, use the
// default" (render/show). `null === false` is `false`, same as `undefined === false`, so `null`
// here preserves that guard behavior for the rare case where the `settings` singleton itself is
// missing, instead of silently flipping to fail-closed (which would 404 three public routes) as a
// side effect of this object existing. Note `null` does NOT trigger a JS default parameter the way
// `undefined` does — `Layout.tsx` explicitly coalesces `settings?.showX ?? true` before passing
// these flags to `Navbar`, so nav-link visibility fails open the same way the route guards do.
export const fallbackSettings: SettingsPayload = {
  siteName: null,
  shortName: null,
  menuItems: [],
  showPublications: null,
  showPeople: null,
  showContactForm: null,
  showLabHeadOnHome: null,
  showLabHeadOnPeople: null,
  contact: null,
  labHead: null,
  footer: [],
  ogImage: null,
  brandColor: null,
  theme: null,
  logo: null,
  logoDark: null,
  icon: null,
}
