import type { Image } from 'sanity'
import type {
  HomePageQueryResult,
  PagesBySlugQueryResult,
  ProfileQueryResult,
  ProjectBySlugQueryResult,
  PublicationsQueryResult,
  SettingsQueryResult,
} from 'sanity.types'

export interface MilestoneItem {
  description?: string
  duration?: {
    start?: string
    end?: string
  }
  image?: Image
  tags?: string[]
  title?: string
}

// Page payloads — derived from `sanity.types.ts` (generated by `npm run typegen` from the actual
// GROQ queries in `lib/sanity.queries.ts`). Every field TypeGen says can be null is typed
// `T | null` here, not silently widened to non-null — callers must handle it explicitly.

export type HomePagePayload = NonNullable<HomePageQueryResult>
export type ShowcaseProject = NonNullable<
  HomePagePayload['showcaseProjects']
>[number]

export type PagePayload = NonNullable<PagesBySlugQueryResult>

export type ProjectPayload = NonNullable<ProjectBySlugQueryResult>

export type SettingsPayload = NonNullable<SettingsQueryResult>
export type MenuItem = NonNullable<SettingsPayload['menuItems']>[number]

export type PublicationPayload = PublicationsQueryResult[number]

export type ProfilePayload = ProfileQueryResult[number]

// `SettingsPayload` now requires every key (nullable values are fine, but the keys themselves
// must be present) — the seven call sites that used to fall back to a bare `?? {}` need a real
// object satisfying that shape. Shared here so it's defined once, not duplicated seven times.
//
// The three `show*` booleans are `null`, not `false`: the pre-existing `?? {}` fallback left them
// `undefined`, which every consuming route's `=== false` notFound() guard and Navbar's
// `showX = true` default parameter both treat as "unset, use the default" (render/show) rather
// than "explicitly disabled." Using `null` here preserves that fail-open behavior for the rare case
// where the `settings` singleton itself is missing, instead of silently flipping to fail-closed
// (which would 404 three public routes and hide their nav links) as a side effect of this object
// existing.
export const fallbackSettings: SettingsPayload = {
  menuItems: [],
  showPublications: null,
  showPeople: null,
  showContactForm: null,
  footer: [],
  ogImage: null,
}
